### ISSUE TITLE
Avoid echoing PHP strings with mark-up in them

### ISSUE THREAD

**Issue by mandiwise** [redacademy/cfs-ws1-2018#10]
For an example, see the `about-entry-content` div page-hero-php. (But I noticed this issue in other templates, so please fix it there too.)

To make your template files more readable, write out the mark-up normally, and simply add PHP tags inside the mark-up tags that echo out the values stored in the variables.

**Comment by Lcunha25** [comment]
I have changed that on the page hero and take part page. If I find it anywhere else will change it.
Thank you.
