### ISSUE TITLE
Do not use WP_Query where it's not needed

### ISSUE THREAD

**Issue by mandiwise** [redacademy/cfs-ws1-2018#11]
In `single-exhibition.php` you are using WP Query to get 11 exhibition posts.

The first issue is that a "single" template is designed for fetching one exhibition (this is what the WordPress loop will fetch by default!). So this is what it should be used for. Use the exhibition archive template for fetching more than one exhibition post at a time.

Further, use the default "if have posts, while have posts, the posts..." loops in your templates wherever possible...don't reinvent the wheel with WP Query. The WordPress template hierarchy will do the work for you if you select the right template.

Third, if there was actually a case for using a custom loop here, remember that unless you need to paginate results, use `get_posts` instead of `WP_Query`.

Lastly, use `pre_get_posts` to change the number of posts you get back in a default loop if needed.

**Comment by kachniss** [comment]
Hi Mandi.

We discussed the details about the `WP_Query` with Anvit on Saturday  and concluded to keep it as it is as the `WP_Query` is only used to display the exhibition menu in the `single-exhibition.php`.
