### ISSUE TITLE
Hide blog functionality if it's not needed

### ISSUE THREAD

**Issue by mandiwise** [redacademy/cfs-ws1-2018#13]
If a WP site doesn't need a blog, as a best practice, hide the posts interface from your client so they don't start adding things in there!

Here's little plugin a wrote to do exactly that: https://gist.github.com/mandiwise/2ea571ae0773b340af5a

If you add this plugin to a `hide-default-posts.php` file in your plugins directory and activate it, the Post editing interfaces in WP will be hidden from the client's view.

*And don't forget to disable comments on the site too.*

**Comment by kachniss** [comment]
I used the plugin. And about disabling comments; is it enough to go to Settings -> Discussion and uncheck the first three checkboxes?
