### ISSUE TITLE
Provide helpful description for all custom fields

### ISSUE THREAD

**Issue by mandiwise** [redacademy/cfs-ws1-2018#7]
For example, you have an icon custom field for exhibitions but could provide helpful information to the client about what (minimum) size the icon should be when uploaded.

Also, what kind of metadata should the client include in the "metadata" field. This may be open-ended, but you should provide them some guidance.

**Comment by Lcunha25** [comment]
I have updated the main database with descriptions for all custom posts and custom fields.
